version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_assistant
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=production
      - WEBHOOK_URL=${MY_DYNAMIC_URL}
      - GENERIC_TIMEZONE=America/Guayaquil
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - gustav_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://n8n_assistant:5678
    networks:
      - gustav_network

networks:
  gustav_network:
    driver: bridge